"""add model provider/config/ab tables

Revision ID: 100d1b19250f
Revises: 
Create Date: 2026-06-14 00:48:35.260016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100d1b19250f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ab_test_rules_target_enabled', 'ab_test_rules', ['target', 'enabled'], unique=False)
    op.create_table('model_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_providers_name'), 'model_providers', ['name'], unique=True)
    op.create_index(op.f('ix_model_providers_provider_type'), 'model_providers', ['provider_type'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('input_price', sa.Float(), nullable=False),
    sa.Column('output_price', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default_chat', sa.Boolean(), nullable=False),
    sa.Column('is_default_emb', sa.Boolean(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_name', name='uq_provider_model_name')
    )
    op.create_index(op.f('ix_model_configs_model_type'), 'model_configs', ['model_type'], unique=False)
    op.create_index('ix_model_configs_provider_id', 'model_configs', ['provider_id'], unique=False)
    op.create_index('uq_default_chat', 'model_configs', ['is_default_chat'], unique=True, sqlite_where=sa.text('is_default_chat = 1'), postgresql_where=sa.text('is_default_chat = true'))
    op.create_index('uq_default_emb', 'model_configs', ['is_default_emb'], unique=True, sqlite_where=sa.text('is_default_emb = 1'), postgresql_where=sa.text('is_default_emb = true'))
    op.create_table('ab_test_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('ab_rule_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.SmallInteger(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ab_rule_id'], ['ab_test_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['model_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_ab_rule', 'ab_test_metrics', ['ab_rule_id'], unique=False)
    op.create_index('ix_metrics_model_created', 'ab_test_metrics', ['model_id', 'created_at'], unique=False)
    op.create_index('ix_metrics_user_created', 'ab_test_metrics', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_user_created', table_name='ab_test_metrics')
    op.drop_index('ix_metrics_model_created', table_name='ab_test_metrics')
    op.drop_index('ix_metrics_ab_rule', table_name='ab_test_metrics')
    op.drop_table('ab_test_metrics')
    op.drop_index('uq_default_emb', table_name='model_configs', sqlite_where=sa.text('is_default_emb = 1'), postgresql_where=sa.text('is_default_emb = true'))
    op.drop_index('uq_default_chat', table_name='model_configs', sqlite_where=sa.text('is_default_chat = 1'), postgresql_where=sa.text('is_default_chat = true'))
    op.drop_index('ix_model_configs_provider_id', table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_model_type'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_model_providers_provider_type'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_name'), table_name='model_providers')
    op.drop_table('model_providers')
    op.drop_index('ix_ab_test_rules_target_enabled', table_name='ab_test_rules')
    op.drop_table('ab_test_rules')
    # ### end Alembic commands ###
